name: bubble_showcase
description: BubbleShowcase is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
version: 0.2.0+4
homepage: https://github.com/Skyost/BubbleShowcase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=0.5.7 <2.0.0'

dev_dependencies:
  pedantic: ^1.9.0