name: bubble_showcase
description: BubbleShowcase is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
version: 1.0.0+6
homepage: https://github.com/Skyost/BubbleShowcase

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5

dev_dependencies:
  pedantic: ^1.11.0